// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDbw-Ys4ZHE6szZ474ZgKLAV-r4q6BYRts',
    appId: '1:747834012269:web:98cdbd047bd125d2bb8564',
    messagingSenderId: '747834012269',
    projectId: 'dr-shawn-clinic-app',
    authDomain: 'dr-shawn-clinic-app.firebaseapp.com',
    storageBucket: 'dr-shawn-clinic-app.firebasestorage.app',
    measurementId: 'G-LV9ZMN503V',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB4FsQRc7_3vmqtKcIk9grJ-TDrW4Gxb-8',
    appId: '1:747834012269:android:1e7ac6a2d3ee1654bb8564',
    messagingSenderId: '747834012269',
    projectId: 'dr-shawn-clinic-app',
    storageBucket: 'dr-shawn-clinic-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAUgVp5KR57I686dF9vBUXqzl61opFh_D4',
    appId: '1:747834012269:ios:f8156452e256a12abb8564',
    messagingSenderId: '747834012269',
    projectId: 'dr-shawn-clinic-app',
    storageBucket: 'dr-shawn-clinic-app.firebasestorage.app',
    iosBundleId: 'com.example.dentalClinicApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAUgVp5KR57I686dF9vBUXqzl61opFh_D4',
    appId: '1:747834012269:ios:f8156452e256a12abb8564',
    messagingSenderId: '747834012269',
    projectId: 'dr-shawn-clinic-app',
    storageBucket: 'dr-shawn-clinic-app.firebasestorage.app',
    iosBundleId: 'com.example.dentalClinicApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDbw-Ys4ZHE6szZ474ZgKLAV-r4q6BYRts',
    appId: '1:747834012269:web:aa34d259ed847166bb8564',
    messagingSenderId: '747834012269',
    projectId: 'dr-shawn-clinic-app',
    authDomain: 'dr-shawn-clinic-app.firebaseapp.com',
    storageBucket: 'dr-shawn-clinic-app.firebasestorage.app',
    measurementId: 'G-RQXMXQ0GYL',
  );
}
